### PR TITLE
Q4 probably

### PR DESCRIPTION
**Pull request by SidneyLovelady**

### CODE REVIEW

**Comment by mtseng15** [comment]
@SidneyLovelady Missing a few things:
- Look at the dockerfile...it's still not correct
- Also need to edit `.gitignore` to ignore all build_product files.

**Comment by SidneyLovelady** [comment]
@mtseng15 This fixed?

**Comment by mtseng15** [comment]
@SidneyLovelady Try running that Dockerfile...it won't run. There's no entry point. I'm not sure how you got another FROM statement in there either.

**Comment by mtseng15** [comment]
Take another crack at it :)

**Pull request closed without merging**
