### PR TITLE
Finally!

### PR DESCRIPTION
**Pull request by JacobM2207**

### CODE REVIEW

**Comment by mtseng15** [comment]
It looks like you manually implemented the changes rather than resetting....did you use reset in an odd mode?

**Comment by JacobM2207** [comment]
I don't think I did. I had to redo this question multiple times before I could finally merge it to the master.

**Comment by mtseng15** [comment]
@JacobM2207 did you use `revert` or `reset`? I don't know how you were able to keep the lines in the Dockerfile for both the bad and good commit...

**Comment by JacobM2207** [comment]
I believe I used revert.

**Comment by mtseng15** [comment]
Screen Shot 2023-02-09 at 8 24 24 PM
@JacobM2207 I'm curious, take a crack at explaining with git how you got both the correct line and Billy Bob Jones' message lines in the Docker file...I'm not sure how that can be done

**Comment by mtseng15** [comment]
I think it's entirely possible, but I just don't know how that could work out. So I'm super curious.

**Comment by JacobM2207** [comment]
I wonder if it’s because I tried to merge to master multiple times. I had
an issue a few times, so I would delete the repository and start again from
the beginning.

**Pull request closed without merging**
